import { Controller, useForm, useWatch } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useInvestorAccountOptions } from '@/entities/account'
import { ORDERS_TABLE, type Order } from '@/entities/order'
import { useProjectOptions } from '@/entities/project'
import { InvestorPickerField } from '@/features/investor-filter'
import { useTableFields } from '@/shared/api/useTableFields'
import { numericText, numberToText } from '@/shared/lib/form'
import { investorLabel } from '@/shared/lib/format'
import {
  DatePicker,
  Field,
  FormFooter,
  FormSection,
  MultiSelect,
  PageLoader,
  Select,
  SwitchField,
  TextField,
} from '@/shared/ui'

// Not here on purpose: `otp` (a one-time password, never shown) and `external_order_id` (generated by the backend).
const multi = z.array(z.string())
const schema = z.object({
  investors_id: z.string(),
  projects_id: z.string(),
  account_id: z.string(),
  type: multi,
  status: multi,
  currency: multi,
  from_account: multi,
  to_account: multi,
  amount_uzs: numericText,
  amount_usd: numericText,
  amount_uzs_with_fee: numericText,
  amount_usd_with_fee: numericText,
  transaction_fee: numericText,
  insurance: numericText,
  is_insurance: z.boolean(),
  currency_rate: numericText,
  deposit_maturity_date: z.string().nullable(),
  transaction_id: z.string().trim(),
})

export type OrderFormValues = z.infer<typeof schema>

const MULTI = ['type', 'status', 'currency', 'from_account', 'to_account'] as const
const NUMBERS = [
  'amount_uzs',
  'amount_usd',
  'amount_uzs_with_fee',
  'amount_usd_with_fee',
  'transaction_fee',
  'insurance',
  'currency_rate',
] as const

interface OrderFormProps {
  order?: Order
  submitLabel: string
  cancelTo: string
  onSubmit: (values: OrderFormValues) => void
}

export function OrderForm({ order, submitLabel, cancelTo, onSubmit }: OrderFormProps) {
  const fields = useTableFields(ORDERS_TABLE)
  const projects = useProjectOptions()
  const {
    register,
    control,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<OrderFormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      investors_id: order?.investorId ?? '',
      projects_id: order?.projectId ?? '',
      account_id: order?.accountId ?? '',
      type: order?.type ?? [],
      status: order?.status ?? [],
      currency: order?.currency ?? [],
      from_account: order?.fromAccount ?? [],
      to_account: order?.toAccount ?? [],
      amount_uzs: numberToText(order?.amountUzs),
      amount_usd: numberToText(order?.amountUsd),
      amount_uzs_with_fee: numberToText(order?.amountUzsWithFee),
      amount_usd_with_fee: numberToText(order?.amountUsdWithFee),
      transaction_fee: numberToText(order?.transactionFee),
      insurance: numberToText(order?.insurance),
      is_insurance: order?.isInsurance ?? false,
      currency_rate: numberToText(order?.currencyRate),
      deposit_maturity_date: order?.depositMaturityDate?.slice(0, 10) ?? null,
      transaction_id: order?.transactionId ?? '',
    },
  })
  const investorId = useWatch({ control, name: 'investors_id' })
  const accounts = useInvestorAccountOptions(investorId || null)

  if (fields.isPending) return <PageLoader label="Loading form" />
  const L = fields.fieldLabel

  return (
    <form noValidate onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-6">
      <FormSection title="Who and what">
        <Controller
          control={control}
          name="investors_id"
          render={({ field }) => (
            <InvestorPickerField
              label={L('investors_id')}
              value={field.value}
              onChange={(id) => {
                field.onChange(id)
                setValue('account_id', '') // accounts belong to an investor
              }}
              initialLabel={
                order?.investorId
                  ? investorLabel(order.investorName, order.investorPhone)
                  : undefined
              }
            />
          )}
        />
        <Field
          label={L('account_id')}
          htmlFor="account_id"
          hint={investorId ? undefined : 'Pick an investor first'}
        >
          <Controller
            control={control}
            name="account_id"
            render={({ field }) => (
              <Select
                id="account_id"
                value={field.value || undefined}
                onChange={field.onChange}
                options={accounts.options}
                disabled={!investorId}
                placeholder={accounts.isFetching ? 'Loading…' : 'Select'}
              />
            )}
          />
        </Field>
        <Field label={L('projects_id')} htmlFor="projects_id">
          <Controller
            control={control}
            name="projects_id"
            render={({ field }) => (
              <Select
                id="projects_id"
                value={field.value || undefined}
                onChange={field.onChange}
                options={projects.options}
              />
            )}
          />
        </Field>
        <TextField label={L('transaction_id')} className="num" {...register('transaction_id')} />
        {MULTI.map((name) => (
          <Field key={name} label={L(name)} htmlFor={name}>
            <Controller
              control={control}
              name={name}
              render={({ field }) => (
                <MultiSelect
                  id={name}
                  value={field.value}
                  onChange={field.onChange}
                  options={fields.fieldOptions(name)}
                />
              )}
            />
          </Field>
        ))}
      </FormSection>

      <FormSection title="Amounts">
        {NUMBERS.map((name) => (
          <TextField
            key={name}
            label={L(name)}
            numeric
            error={errors[name]?.message}
            {...register(name)}
          />
        ))}
        <Controller
          control={control}
          name="is_insurance"
          render={({ field }) => (
            <SwitchField
              label={L('is_insurance')}
              checked={field.value}
              onChange={field.onChange}
            />
          )}
        />
        <Field label={L('deposit_maturity_date')} htmlFor="deposit_maturity_date">
          <Controller
            control={control}
            name="deposit_maturity_date"
            render={({ field }) => (
              <DatePicker
                id="deposit_maturity_date"
                value={field.value}
                onChange={field.onChange}
              />
            )}
          />
        </Field>
      </FormSection>

      <FormFooter cancelTo={cancelTo} submitLabel={submitLabel} />
    </form>
  )
}
